# Generated by Django 4.2.7 on 2023-11-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('f_name', models.CharField(max_length=30)),
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=25)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.author')),
            ],
        ),
    ]
